version: '3'
services:
  go:
    build: .
    ports:
      - 8000:8000
      - 8080:8080
    volumes:
      - .:/go/src/app:cached
    depends_on:
      - 'db'
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    volumes:
      - ./db_data:/var/lib/mysql
      - ./localhost.sql:/docker-entrypoint-initdb.d/install_db.sql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "development"
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"